import NavBar from "./components/NavBar/navbar";
import Footer from "./components/footer/footer";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
      </body>
      <Footer />
      {/* <body className={inter.className}><NavBar/>{ children}</body> */}
    </html>
  );
}
